### ISSUE TITLE
Haxe 3.3 Error with PyHelpers.hx

### ISSUE THREAD

**Issue by ustutz** [andyli/haxe-usage-survey#1]
Hallo,
i get an error message when compiling using PyHelpers with Haxe 3.3.
PyHelpers.hx:49: characters 25-82 : Cannot use Void as value

In Haxe 3.2 everything works fine. Is this a Haxe bug or a bug in PyHelpers?

For an example see
https://github.com/ustutz/dataquest/tree/master/Data_Analyst/Step_2_Intermediate_Python_and_Pandas/2_Data_Analysis_with_Pandas_Intermediate/1_Getting%20started%20with%20NumPy/4_Using_NumPy

**Comment by andyli** [comment]
Should be fixed by 5ab030af6bc91d871829ccd5bb85373385cbd716. Please test ;)

**Comment by ustutz** [comment]
Yes it works! :-) Thank you.

**Comment by andyli** [comment]
Good to know! :)
